[profile.default]
src = 'src'
out = 'out'
libs = [ 'lib' ] # See more config options https://github.com/foundry-rs/foundry/tree/master/config
viaIR = true
allow_paths = ['../../node_modules', '../../node_modules/@zk-email/contracts']
solc_version = '0.8.21'


[profile.gas_price] 
sepolia = 300_000_000_000
gas_limit = 1073741824
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 0
block_difficulty = 0
block_prevrandao = '0x0000000000000000000000000000000000000000'
block_gas_limit = 30000000